### PR TITLE
update npm registry URL #3

### PR DESCRIPTION
**Pull request by mreinstein**

### CODE REVIEW

**Comment by davidmarkclements** [comment]
your commit "don't checkin node_modules" it err.. checks in node_modules 

they weren't checked in before were they?

**Comment by mreinstein** [comment]
it appears `node_modules` has been checked in since the first commit: https://github.com/davidmarkclements/npm-dependents/tree/306a78c7075131ddaef84813658467cab535fe31

**Comment by davidmarkclements** [comment]
LOL!

**Comment by davidmarkclements** [comment]
thank you for the PR

**Comment by mreinstein** [comment]
thanks for merging it so quicky!

**Comment by davidmarkclements** [comment]
1.0.3 published

**Pull request merged**
